[variables]
# PostgreSQL Configuration
POSTGRES_DB = "${POSTGRES_DB}"
POSTGRES_USER = "${POSTGRES_USER}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
PGDATA = "/var/lib/postgresql/data"

# MinIO Configuration
MINIO_ROOT_USER = "${AWS_ACCESS_KEY_ID}"
MINIO_ROOT_PASSWORD = "${AWS_SECRET_ACCESS_KEY}"

[providers]
postgres = "docker"
minio = "docker"

[phases.setup]
cmds = ["apt-get update", "apt-get install -y docker.io"]

[phases.install]
cmds = [
    # Pull Supabase PostgreSQL image
    "docker pull supabase/postgres:15.6.1.113",
    # Pull MinIO image
    "docker pull minio/minio:latest",
]

[phases.build]
cmds = [
    # Create data directories
    "mkdir -p /var/lib/postgresql/data",
    "mkdir -p /data",
]

[start]
cmd = "bash start.sh"

[ports]
postgres = "5432"
minio_api = "9000"
minio_console = "9001"
